### ISSUE TITLE
Should this work?

### ISSUE THREAD

**Issue by m1sta** [jtblin/syncho#5]
Should this work?

    function echo(text, cb) {
        cb(null, text);
    }

    require('syncho')(function(){
        console.log('Before sync');
        console.log(echo.sync('Hello!'))
        console.log('After sync');
    });

It doesn't seem to unless the first argument passed to `echo.sync` is null, contrary to the function signature of `echo`.

It feels like it should be more like...

      Function.prototype.sync = function sync () {
       ([]).unshift.call(arguments, null)
        return this.future.apply(this, arguments).wait();
      };

**Comment by m1sta** [comment]
It'd also be great to be able to do the following when a function doesn't follow the err, result pattern...

   var result = getUserById.syncAs(['name', 'address'])(123)
   //result = {name:'John', address:'1 Home Street'}
  
and when you don't want to write try/catch everywhere, create something that slowly begins to look like a stream...

    sync(function(){
        //do stuff that throws an exception
    }).on('error', function(error){})

**Comment by jtblin** [comment]
Regarding your first issue, as explained in the readme, `syncho` follows the `Function.prototype.call` [signature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call) with the `thisArg` first. This is needed for prototype's functions which need to refer to `this`. Otherwise the only way to pass `this` would be to bind which would give something like `fs.readFileSync.bind(this).sync(pathname)` which isn't ideal either. As the `Function.prototype.call`  signature is the convention in js (call, apply, bind), I thought it was a better choice.

**Comment by jtblin** [comment]
Re: functions callback that do not follow the `err, res` patten, this is out of scope for this project. The goal was to keep it simple and fast. Error-first callback is also a convention in node, and followed by the majority of the libraries.  You can easily use a wrapper for functions that don't.

**Comment by jtblin** [comment]
Re: following the event emitter convention, although I can see the benefit of getting the error with a callback, I really don't see the point of "could we create something that slowly begins to look like a stream...". Streams is a control flow pattern for asynchronous functions, `syncho` and `Fibers` are already a control flow pattern that allow to write code **synchronously** i.e. to avoid using callbacks, promises or event emitter patterm so having something that looks like a stream doesn't have any interest. 

And you know this is open-source, you can always fork the project and change the style to be whatever you'd like as it seems that's what you have issues with, or even sending a pull request instead of snarky comments... or even do not bother using it at all.
